[DEFAULT] # protected table name
samples = 4
skip_transient_states = 1
desired_stable_states = 5000
dimensions = [25,25]
initial_condition = "rational_0_1"
boundary_condition = "cliff"
perturbation_scheme = "global_maximise"
control_scheme = "none"
update_rule = "OFC"
activity_setting = "proactive"

[1]
samples = 1
[2]
skip_transient_states = 1000
desired_stable_states = 6000
[3]
samples = 1
skip_transient_states = 1000
desired_stable_states = 6000

[3D]
dimensions = [10,10,10]

[BRIEF]
samples = 2
skip_transient_states = 5
desired_stable_states = 10
[BRIEF_CONTROL]
samples = 2
skip_transient_states = 5
desired_stable_states = 10
control_scheme = "manual_perturbation_series_mass_lt_critical_random_1_true"

[FAST]
samples = 2
desired_stable_states = 500
dimensions = [10,10]

# ste: ~00:25:00 -> ~00:00:10
[SLOW]
samples = 10
skip_transient_states = 5000
desired_stable_states = 30000
dimensions = [50,50]
[SLOW_CONTROL_LT]
samples = 10
skip_transient_states = 5000
desired_stable_states = 30000
dimensions = [50,50]
control_scheme = "manual_perturbation_series_mass_lt_critical_random_1_true"
[SLOW_CONTROL_GT]
samples = 10
skip_transient_states = 5000
desired_stable_states = 30000
dimensions = [50,50]
control_scheme = "manual_perturbation_series_mass_gt_critical_random_1_true"

# [MANY_QUICK]
# samples = 20
# desired_stable_states = 1000
# dimensions = [10,10]

[SINGLE]
initial_condition = "rational_0_1"
samples = 1
desired_stable_states = 200000
dimensions = [50,50]

[SINGLE_CONTROL]
initial_condition = "rational_0_1"
samples = 1
desired_stable_states = 200000
dimensions = [50,50]
control_scheme = "manual_perturbation_series_mass_lt_critical_random_1_true"

[BTW_DEFAULT]
initial_condition = "integer_10_30"
perturbation_scheme = "random_1"
update_rule = "ABS"

# [BTW_SLOW]
# samples = 10
# desired_stable_states = 10000
# dimensions = [50,50]
# initial_condition = "integer_10_30"
# perturbation_scheme = "random_1"
# update_rule = "ABS"

[BTW_SINGLE]
samples = 1
desired_stable_states = 100000
dimensions = [30,30]
initial_condition = "integer_10_30"
perturbation_scheme = "random_1"
update_rule = "ABS"

[BTW_CONTROL_SINGLE]
samples = 1
desired_stable_states = 100000
dimensions = [30,30]
initial_condition = "integer_10_30"
perturbation_scheme = "random_1"
control_scheme = "perturbation_mass_lt_threshold_random_1_true"
update_rule = "ABS"
