[DEFAULT]
samples = 4
desired_stable_states = 5000
dimensions = [25,25]
initial_condition = "rational_10_20"
boundary_condition = "cliff"
perturbation_scheme = "global_maximise"
control_scheme = "none"
update_rule = "OFC"
activity_setting = "proactionary"

[BRIEF]
samples = 2
desired_stable_states = 20

[FAST]
samples = 2
desired_stable_states = 500
dimensions = [10,10]

# ste: ~00:25:00
[SLOW]
samples = 10
desired_stable_states = 10000
dimensions = [50,50]

[MANY_QUICK]
samples = 20
desired_stable_states = 1000
dimensions = [10,10]

[ONE_LONG]
samples = 1
desired_stable_states = 100000
dimensions = [50,50]

[3D]
dimensions = [10,10,10]

[BTW]
initial_condition = "integer_10_30"
perturbation_scheme = "random_1"
update_rule = "ABS"

[CONTROL]
control_scheme = "perturbation_mass_lt_threshold_random_1_true"